language: ruby
script: JEKYLL_ENV=production bundle exec rake build
branches:
  only: master
env:
  global:
  - secure: j8orfC4jzV8uLrkwgI6L0ih4Tqr/96Qpn6jie9LcyQIdkAbgdOAt+BRXIyhKqXmpowKyu0UmFINpXy0sql4AcIti0Xr562pAGJtvsauwh1Mcer/dpsWh88WCnxOTMhlqB/flzorgAqFmvHQZIYJXHy11NLvkCqfU37wRuaWs3wQ=
  - secure: d3F8/KN1jfG2od+iyabLkJwVx+++gUOtTOh9+nG+E3H2w3zCyybU/U7xbiZF6XPpPpi8YNNbmHejH6WNsDcslTPEiL6kIk6ha2fgh+ETy9OSca6UbtBV1ihpB88GOxXoAbUnQSzx3QXyFTmSTKKqKqTSoGvO9cLtKunJY8L9lh0=
  - secure: b7S5/70pOR+vo9x3HeZAl6zfYW6F3LeRnOIqPmJAhslCQ6JZNXrmNvu06hSQsJ8aQjvxH3R3zukfE8onK2SIpHsqaw+sVgcZLvoSUgvM35mQlNQTW9tRoLZQjBRgQMd7MoA3TefDzqx0S+byxlZLF4z3fma7QwPnM4hdCVKiLhA=
  - secure: eeCu7GZ5GHujcFMAms+HwbEAMJhGI6625wVSgO+Jo5i4BSdXV9i1I1Fbz5kfSZ3bO4wfegbLgaWd+9Yrs5RL8GNNdLJ6jezsTU9qTJRr7LkqnxYgGxlIP6/7T9NOnlsLg/Cu6aEr2WpaWLeN4V7wk8cHRkTFJGJ7OsMSlITuMHE=
  - secure: TGxlEb42L1dprwaVeYIbjDa6zQJzn1uaKz2Ihe3F0FRoGpnrqEKEAwBT/v0MCFjEabyfa+oBbrNdQyNkvtGgvPiXH55w3wFacJNQaUzIbW8jcelgJglarSXci4zYvcLG7b6S/XoMRWEFfELe1UoV9iMo8RyrGdPlCSn1Tep0MoA=
cache: bundler
deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_ID"
  secret_access_key: "$S3_ACCESS_SECRET"
  bucket: hugotunius.se
  skip_cleanup: true
  local_dir: _site
  detect_encoding: true
  default_text_charset: utf-8
after_deploy:
- bundle exec rake purge_cloudflare_html_files
